### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Trymunx**
On that hacktoberfest vibe

### CODE REVIEW

**Comment by Humpheh** [comment]
So as this repo is essentially representing myself does that mean that by merging this I am provided "As is", without warranty of any kind, express or Implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors (my parents?) or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with me or the use or other dealings in me.

**Comment by Trymunx** [comment]
IANAL but that sounds exactly how I would expect it to work.

**Comment by Humpheh** [comment]
So as this repo is essentially representing myself does that mean that by merging this I am allowing myself to belong to Alexander Houseago?

**Comment by Trymunx** [comment]
I think I've been rumbled.

**Comment by Humpheh** [comment]
Out of all the repo's too

**Pull request closed without merging**
